### ISSUE TITLE
Make our project website more public-facing.

### ISSUE THREAD

**Issue by samcunliffe** [UCL/TDMS#230]
Following a discussion with @prmunro last week, it'd be good to have a welcoming friendly project website.
Currently, our site (https://github-pages.ucl.ac.uk/TDMS) contains only developer docs and redirects new users to the README.md in the repository.

With doxygen, it's possible to include _multiple_ markdown files which get put in the "Related pages" and included as part of the index...
```bash
# 'mainpage' gets put on the index page
INPUT += README.md
INPUT += CONTRIBUTING.md
INPUT += doc/developers.md
USE_MDFILE_AS_MAINPAGE = README.md
```

Results in:
![Screenshot 2023-02-16 at 15 15 30](https://user-images.githubusercontent.com/1836192/219407404-d4dfc114-df24-462f-a46c-e400dacf3b72.png)

(I.e. contributor guidelines then developer docs (in the order that we'd want because we're lucky with the alphabet).

----

## TODO

- [ ] Make README.md → CONTRIBUTING.md → doc/developers.md flow nicely together (they repeat a bit).
- [ ] Go over README.md and check for clarity.
- [ ] Display department logos and funding agencies?
- [ ] A logo for the web page, or a nice image of light on a sphere, or both.

**Comment by samcunliffe** [comment]
Still some things to iron out. Playing [over on my personal fork of TDMS](https://scnlf.me/TDMS) so as to not break our actual live pages.

**Comment by willGraham01** [comment]
Possibly add a note/request to the end of the readme: (from 28/3/2023 meeting)
If you use TDMS frequently and have example use cases that you don't mind/would like to share, please get in touch at `<foobar>`.
