### ISSUE TITLE
Classes to detach from MATLAB

### ISSUE THREAD

**Issue by willGraham01** [UCL/TDMS#285]
Essentially a tracker for our progress towards #70.

# Logging which `tdms` classes need to be detached from MATLAB

## Non-MATLAB classes we might want to flatten
Whilst it won't be necessary (we can just reshape buffers before writing/reading) we might want to rework the classes below to have flat, strided vectors to store their data rather than pointers to pointers.
- [x] `Tensor3D`
- [x] `Matrix`

## Storage classes
Classes that are inherited from by other classes, or are simply used to store or interact with MATLAB objects.
- [x] `MaterialCollection` (#315)
- [x] `CCollectionBase` (#315)
- [x] `DCollectionBase` (#315)
- [ ] `Vector` (this class can almost surely be replaced with `std::vector` now that we can read MATLAB buffers via HDF5).
- [ ] `Dimensions` (this could quite easily be replaced with `H5Dimensions` from #281)
- [ ] `Field`
- [ ] `SplitField`
- [ ] `LoopVariables` (just for the copy of the electric field at the previous iteration)

## Classes that are only read into
Classes that are read from the input file, or initialised by passing `mxArray` pointers.
- [x] `CMaterial` (inherits `MaterialCollection`, `CCollectionBase`) (#315)
- [x] `DMaterial` (inherits `MaterialCollection`, `DCollectionBase`) (#315)
- [x] `DispersiveMultiLayer`
- [ ] `GratingStructure` (inherits `Matrix`)
- [x] `FrequencyExtractVector` (#328)
- [x] `FrequencyVectors`
- [x] `Pupil` (inherits `Matrix`)
- [ ] `DTilde` (inherits `Tensor3D`)
- [ ] `IncidentField` (inherits `Tensor3D`)
- [ ] `fdtdGridInitialiser`
- [x] `InterfaceComponent`
- [x] `Cuboid`
- [ ] `Source` (requires `complex` casting)

## Classes that are written out
Classes that need some (or all) of their data written to the output file.
- [x] `FieldComponentsVectors` (inherits `Vector`, part of `VertexPhasors`) (#328)
- [ ] `Vertices` (inherits `Matrix`, part of `VertexPhasors`)
- [ ] `ElectricField` (inherits `Field`)
- [ ] `MagneticField` (inherits `Field`)
- [ ] `FieldSample`
- [ ] `SurfacePhasors`
- [ ] `VertexPhasors`
- [ ] `IDVariables`

## Classes that are both read and written
WYTII.
- [ ] `TDFieldExporter2D`
- [ ] `GridLabels`
- [ ] `SimulatonManager`

## Dependent Functions
Files that define functions that operate on MATLAB objects.
- [ ] `array_init.h/cpp`
- [ ] `mesh_base.h/cpp`
- [ ] `matlabio.h/cpp` (likely will be deleted)
- [ ] `mat_io.h/cpp` (likely will be deleted)

## Other Classes
- [ ] `InputMatrices` can be removed once all functions that need to read into have MATLAB removed. `simulation_manager` will need to be passed the name of the `HDF5` file, or a `HDF5Reader` instance.
- [ ] `OutputMatrices` no longer needs to hold `MATLAB` pointers, instead should use `HDF5Writer` to produce the output. Removing MATLAB from each of the written out classes should involve implementing such functionality in this class, in which case it might be redundant / separated from MATLAB by this stage anyway.

## Test Classes
- [ ] `AbstractArrayTestClass` and all its dependencies will need to be adjusted accordingly. Recommend doing this whilst tackling each class that is tested by this.
