### ISSUE TITLE
Modify interpolation scheme

### ISSUE THREAD

**Issue by t-young31** [UCL/TDMS#44]
Overhaul interpolation from the split grid to the central grid. 

1. Different scheme required for each field component.
2. Is implemented for the electric field, although interpolateTimeDomainFieldCentralEBandLimited was hacked to work for the 2D case, this should be checked.
3. More significant work required for the magnetic field
4. Enable interpolation to be performed right up to the edge of the computational domain.

***
### Dependencies:

- [x] Theoretical outline from @prmunro 

***
### Tasks specified in `PSTD_interpolation_scheme.pdf`:

- [x] Write (time-domain) interpolation methods for E-field components. Should use BLi, and if not possible, fall back on cubic interpolation. Closed by #62.
- [x] Write (time-domain) interpolation methods for H-field components using the 2D-method interpolation method. Interpolation in each dimension should again use BLi if possible, and failing that fall back on cubic. Closed by #62.
- [x] #112
- [x] Unit tests for cubic interpolation methods. Closed by #62.
- [x] #111
- [x] #110
- [ ] #109
- [x] #113
- [ ] #114
- [x] #115

**Comment by giordano** [comment]
Related to interpolation, there are many interpolation functions which are supposed to return `int`, but the return value is never actually used.  For example https://github.com/UCL/TDMS/blob/805e5dd601168ea1bfb16e32d3dd326c6a397302/tdms/src/interpolate.cpp#L1086 can return `-1` under certain conditions https://github.com/UCL/TDMS/blob/805e5dd601168ea1bfb16e32d3dd326c6a397302/tdms/src/interpolate.cpp#L1094-L1096 but its use at https://github.com/UCL/TDMS/blob/805e5dd601168ea1bfb16e32d3dd326c6a397302/tdms/src/tdms_iterator.cpp#L6174-L6176 doesn't check the return value, so that an error would never be caught.

I guess these functions should either be `void` and throw errors when needed, or at very least the return values should be checked and appropriately dealt with.

**Comment by willGraham01** [comment]
Adding another task list to this issue in light of the information we have from the shared document `PSTD_interpolation_scheme.pdf`.

- [x] Write (time-domain) interpolation methods for E-field components. Should use BLi, and if not possible, fall back on cubic interpolation. Closed by #62.
- [ ] Write (time-domain) interpolation methods for H-field components using the 2D-method interpolation method. Interpolation in each dimension should again use BLi if possible, and failing that fall back on cubic.
- [ ] Write interpolation methods for the E- and H- fields in the frequency domain. Compared to the time-domain, this scheme must be able to handle complex data.
- [x] Unit tests for cubic interpolation methods. Closed by #62.
- [ ] Unit tests for BLi interpolation methods.
- [ ] Unit tests for `interpolate{TimeDomain,FrequencyDomain}{E,H}{x,y,z}` functions.
- [ ] `fieldsample` does not allow for extraction of magnetic field at the vertices - this must be added.
- [ ] Change the interpolation calls in `exphasorssurface`, `exphasorsvolume`, and `fieldsample` to the new interpolation functions.

**Comment by samcunliffe** [comment]
Closing as this as done: #44 can stay open until someone with research time wants to take it on, and #109 will be addressed independently.
